// Component
import Head from "next/head";
import About from "../components/About/about";
import Blog from "../components/Blog/blog";
import Featured from "../components/Featured/featured";
import Hero from "../components/Hero/hero";
import LetsTalk from "../components/letsTalk/letsTalk";
import Portfolio from "../components/Portfolio/portfolio";
import Service from "../components/Service/service";
import Team from "../components/Team/team";
import Testimonial from "../components/Testimonial/testimonial";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Game Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <About />
      <Service />
      <Testimonial />
      <Portfolio />
      <Featured />
      <Team />
      <Blog />
      <LetsTalk />
    </div>
  );
}
